name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ejecutar tests de Práctica 4
        run: node practica-4/fiados.test.js

      - name: Ejecutar tests de Práctica 5
        run: node practica-5/enfermo.test.js